name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: apt-update
      run: sudo apt-get update -qq
    - name: apt get glfw
      run: sudo apt-get install -y --no-install-recommends libglfw3 libglfw3-dev libglew-dev
    - name: build opengl2
      run: make -C demo/glfw_opengl2
    - name: build opengl3
      run: make -C demo/glfw_opengl3
    - name: build example
      run: make -C example
